/**
 * Typed accessors over the ingested real data (src/data/generated/*).
 * Generated by scripts/ingest.mjs from the platform's on-disk artifacts.
 * If the data dir was absent at build time, files carry `{ fixture: true }`.
 */
import overviewJson from "./generated/overview.json";
import experimentsJson from "./generated/experiments.json";
import graphJson from "./generated/graph.json";
import benchmarksJson from "./generated/benchmarks.json";
import datasetJson from "./generated/dataset.json";
import evaluationJson from "./generated/evaluation.json";
import papersJson from "./generated/papers.json";
import operatorsJson from "./generated/operators.json";
import provenanceJson from "./generated/provenance.json";
import proposalsJson from "./generated/proposals.json";
import modelsJson from "./generated/models.json";
import behaviourJson from "./generated/operator_behaviour.json";

export type Rollup = { key: string; runs: number; meanImpr: number; best: number | null };
export type Overview = {
  primary: string;
  totals: { runsPrimary: number; runsAll: number; instances: number; operators: number; backends: string[]; generations: number };
  best: { score: number; baseline: number; instance: string; seq: string[]; seed: string } | null;
  perCampaign: { label: string; runs: number; instances: number; generations: number }[];
  graphFactCount: number;
  latestPaper: { file: string; experiments: number | null; best: string | null; discoveries: { text: string; support: number; confidence: number }[] } | null;
};
export type ExpRow = {
  id: number; instance: string; seq: string[]; backend: string; score: number; baseline: number; impr: number;
  sweeps: number[]; seed: string; tempHi: number; tempLo: number; replicas: number; n: number; density: number;
  campaign: number; generation: number; wallMs: number;
};
export type Experiments = {
  totalRows: number; sample: ExpRow[];
  rollups: { byOperator: Rollup[]; byBackend: Rollup[]; byInstance: Rollup[]; byCampaign: Rollup[] };
  histogram: { bins: number[]; min: number; max: number };
};
export type Fact = { subject: string; relation: string; object: string; weight: number; support: number; variance: number; confidence: number | null; source: string };
export type Graph = { facts: Fact[]; relations: string[]; nodes: string[] };
export type Provenance = { generatedFrom: string; primary?: string; fixture?: boolean; sources: { label: string; file: string; rows: number; mtime: string | null; exists: boolean }[] };

const isFixture = (o: unknown): boolean => !!(o as { fixture?: boolean })?.fixture;

export const overview = overviewJson as unknown as Overview;
export const experiments = experimentsJson as unknown as Experiments;
export const graph = graphJson as unknown as Graph;
export const benchmarks = benchmarksJson as unknown as {
  index: { runs: { exp: string; ts: string; per_engine: Record<string, { mean_best: number; mean_wall_ms: number; head_to_head?: { vs: string; instances: number; win_fraction: number; wilcoxon_p: number; sign_test_p: number } }> }[] } | null;
  specs: { id: string; title: string; status: string; hypothesis: string; kill_criterion: string }[];
};
export const dataset = datasetJson as unknown as {
  examples: number; instances: number; operators: number;
  milestones: { milestone: number; examples: number; reached: boolean; multiplier: number }[]; markdown: string;
};
export const evaluation = evaluationJson as unknown as {
  rows: { signature: string; family: string; instances: number; confidence: number; example: string }[]; markdown: string;
};
export const papers = papersJson as unknown as {
  file: string; experiments: number | null; best: string | null;
  discoveries: { text: string; support: number; confidence: number }[]; markdown: string;
}[];
export const operators = operatorsJson as unknown as { operators: string[]; rollup: Rollup[] };
export const provenance = provenanceJson as unknown as Provenance;

export type Proposal = {
  file: string; name: string; provenance: string; idea: string; math: string;
  pseudocode: string; properties: string[]; capabilities: string[]; complexity: string; status: string;
};
/** Mined operator proposals — real research leads from meta_learner gaps. */
export const proposals = proposalsJson as unknown as Proposal[];

export type ModelSnapshot = {
  campaign: string; kind: string; version: number; parent: number | null;
  campaign_id: number; generation_id: number; instance: string;
  trained_on: number; timestamp: number; payload_bytes: number;
};
/** Versioned model snapshots with lineage (model_registry.txt). Metadata only —
 *  the weight payloads are deliberately not shipped to the client. */
export const models = modelsJson as unknown as ModelSnapshot[];

export type OperatorSignature = { signature: string; family: string; instances: number; confidence: number; example: string };
export type OperatorBehaviour = {
  operator: string;
  rollup: Rollup | null;
  signatures: OperatorSignature[];
  facts: { relation: string; object: string; weight: number; support: number; confidence: number | null }[];
  discoveries: { text: string; support: number; confidence: number }[];
};
/** Everything the record knows about each operator, keyed by name. */
export const behaviour = behaviourJson as unknown as Record<string, OperatorBehaviour>;

export const dataAvailable = !isFixture(overviewJson);
export const provFor = (labelIncludes: string) =>
  provenance.sources?.find((s) => s.label.includes(labelIncludes)) ?? null;
