import { proposals, provenance } from "@/data";
import { computeGaps, KIND_META } from "@/lib/workflow/gaps";
import { Eyebrow, Panel, PanelHeader, Pill, ProvenanceTag, Icon } from "@/components/os/kit";
import Guide from "@/components/os/workflow/Guide";
import Spine from "@/components/os/workflow/Spine";
import { TrackVisit } from "@/components/os/workflow/Track";
import GapList from "@/components/os/workflow/GapList";

export default function DiscoverPage() {
  const gaps = computeGaps();
  const src = provenance.sources?.find((s) => s.label === "proposals");

  return (
    <div className="mx-auto max-w-[1240px] px-5 py-8 md:px-8">
      <TrackVisit route="/discover" />
      <div className="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
          <Eyebrow n="◇">Discovery Center</Eyebrow>
          <h1 className="max-w-[30ch] text-[clamp(1.6rem,2.6vw,2.3rem)] font-semibold tracking-[-.025em]">
            Where the map ends — gaps the platform found in its own knowledge.
          </h1>
          <p className="mt-2 max-w-[80ch] text-[13.5px] leading-[1.6] text-[var(--os-muted)]">
            None of this is generated by the interface. Every lead below is derived from a real artifact — a mined
            operator gap, a fact standing on thin support, a rule that failed to reproduce, an underpowered comparison.
            The engine decides what is worth studying; this screen only shows it.
          </p>
        </div>
        <ProvenanceTag file={src?.file} rows={src?.rows} mtime={src?.mtime} />
      </div>

      <Spine route="/discover" activeId="discovery" />
      <Guide route="/discover" />

      {/* mined operator proposals — the highest-leverage leads */}
      <div className="mb-4">
        <div className="mono mb-2.5 flex items-center gap-2 text-[11px] uppercase tracking-[.16em] text-[var(--os-accent)]">
          <Icon name="Sparkles" size={13} /> Mined operator proposals
          <span className="text-[var(--os-faint)]">— a machine-generated research lead</span>
        </div>
        {proposals.length === 0 ? (
          <Panel className="p-5 text-[13px] text-[var(--os-faint)]">No operator proposals in the ingested corpus.</Panel>
        ) : (
          <div className="grid gap-3 lg:grid-cols-2">
            {proposals.map((p) => (
              <Panel key={p.file} ticks className="overflow-hidden">
                <PanelHeader title={p.name} status="real" sub={p.file}
                  right={<Pill tone="open">draft</Pill>} />
                <div className="space-y-3 p-5">
                  <div>
                    <div className="mono text-[9.5px] uppercase tracking-[.14em] text-[var(--os-accent)]">why it was proposed</div>
                    <p className="mt-1 text-[12.5px] leading-[1.55] text-[var(--os-ink)]">{p.provenance}</p>
                  </div>
                  {p.idea && (
                    <div>
                      <div className="mono text-[9.5px] uppercase tracking-[.14em] text-[var(--os-faint)]">idea</div>
                      <p className="mt-1 text-[12.5px] leading-[1.55] text-[var(--os-muted)]">{p.idea}</p>
                    </div>
                  )}
                  {p.pseudocode && (
                    <div>
                      <div className="mono text-[9.5px] uppercase tracking-[.14em] text-[var(--os-faint)]">pseudocode</div>
                      <pre className="mono mt-1 overflow-x-auto rounded-[8px] border border-[var(--os-hair)] bg-[var(--os-ground)] p-3 text-[11px] leading-[1.55] text-[var(--os-muted)]">{p.pseudocode}</pre>
                    </div>
                  )}
                  <div className="grid gap-3 sm:grid-cols-2">
                    {p.properties.length > 0 && (
                      <div>
                        <div className="mono text-[9.5px] uppercase tracking-[.14em] text-[var(--os-faint)]">expected properties</div>
                        <ul className="mt-1 space-y-0.5">
                          {p.properties.map((x, i) => <li key={i} className="text-[12px] leading-[1.5] text-[var(--os-muted)]">· {x}</li>)}
                        </ul>
                      </div>
                    )}
                    {p.capabilities.length > 0 && (
                      <div>
                        <div className="mono text-[9.5px] uppercase tracking-[.14em] text-[var(--os-faint)]">required capabilities</div>
                        <ul className="mt-1 space-y-0.5">
                          {p.capabilities.map((x, i) => <li key={i} className="mono text-[11.5px] leading-[1.5] text-[var(--os-muted)]">{x}</li>)}
                        </ul>
                      </div>
                    )}
                  </div>
                  {p.complexity && (
                    <div className="mono border-t border-[var(--os-hair)] pt-2.5 text-[11px] text-[var(--os-faint)]">
                      complexity: <span className="text-[var(--os-muted)]">{p.complexity}</span>
                    </div>
                  )}
                  <p className="mono border-t border-[var(--os-hair)] pt-2.5 text-[10.5px] leading-[1.5] text-[var(--os-warn)]">
                    A proposal is a research artifact, not code. The platform deliberately writes no Rust here — an
                    operator must pass the harness checker before it can join the verified set.
                  </p>
                </div>
              </Panel>
            ))}
          </div>
        )}
      </div>

      {/* the ranked gap list (client component: records the mission action) */}
      <GapList gaps={gaps} meta={KIND_META} />

      {/* what is still missing to make this complete */}
      <Panel className="mt-4 p-5">
        <div className="mono mb-2 text-[11px] uppercase tracking-[.16em] text-[var(--os-muted)]">Not yet shown here</div>
        <p className="max-w-[86ch] text-[13px] leading-[1.6] text-[var(--os-muted)]">
          The engine also computes three curiosity signals — <span className="text-[var(--os-ink)]">disagreement</span> (where its
          own predictor is wrong), <span className="text-[var(--os-ink)]">coverage</span> (operators tried rarely or never) and{" "}
          <span className="text-[var(--os-ink)]">anomaly</span> (unstable across seeds) — plus a ranked Planner agenda with a
          reason per item. Those live only in memory today; they need a serialization seam before they can appear here
          honestly. Until then this screen shows what is on disk, and says so.
        </p>
      </Panel>
    </div>
  );
}
