/**
 * Contextual education. Definitions are written for someone becoming a
 * computational scientist — each says what the term means, and why it matters
 * *in this platform*. Where a term maps to real code, the module is named.
 */

export type Term = {
  key: string;
  term: string;
  short: string;
  /** Why a researcher should care. */
  why?: string;
  /** Real module or artifact this concept lives in. */
  where?: string;
};

export const GLOSSARY: Term[] = [
  { key: "ising", term: "Ising model", short: "A lattice of ±1 spins whose energy comes from pairwise couplings; minimising that energy is NP-hard in general.",
    why: "It is the physical form this engine optimises — and a huge family of combinatorial problems reduces to it.", where: "engine_v2/state.rs" },
  { key: "qubo", term: "QUBO", short: "Quadratic Unconstrained Binary Optimisation — minimise xᵀQx over binary x. Equivalent to Ising up to a change of variables.",
    why: "The canonical input format. Any problem you can reduce to QUBO, this engine can attempt.", where: "engine_v2/ir.rs" },
  { key: "operator", term: "Operator", short: "One physical law applied to the spin state — a Metropolis sweep, a cluster move, a greedy descent.",
    why: "The platform searches over *sequences* of operators rather than tuning one monolithic algorithm; that is what lets it discover compositions a human wouldn't try.", where: "engine_v2/registry.rs · 14 operators" },
  { key: "baseline", term: "Baseline", short: "The reference score a run is measured against; improvement is score − baseline.",
    why: "Raw energies are meaningless across instances. Only the delta against a fixed baseline is comparable.", where: "ai_scientist/db.rs" },
  { key: "improvement", term: "Improvement (Δ)", short: "score − baseline. Negative is better, because this is a minimisation.",
    why: "Sign conventions cause more misread results than any other detail. Here, lower is better." },
  { key: "determinism", term: "Determinism", short: "Same seed → same trajectory → same final energy, bit-for-bit.",
    why: "It makes every recorded run replayable and every claim checkable. It is also what makes 'fork this experiment' meaningful.", where: "ADR-0004" },
  { key: "seed", term: "Seed", short: "The RNG initialiser stamped on every recorded run.",
    why: "The seed is the difference between a result and an anecdote — it is the whole reproduction recipe in one number." },
  { key: "bit-identical", term: "Bit-identical replay", short: "Two backends compute the same trajectory to the last bit, verified past 100k spins.",
    why: "It lets a fast production backend be trusted against a slow exact oracle — performance without giving up correctness.", where: "engine_v2 backends" },
  { key: "append-only", term: "Append-only record", short: "Experiments, facts and reports are only ever added, never edited or deleted.",
    why: "History becomes evidence. You can always ask what the system believed, and when — including the things it later abandoned.", where: "ai_scientist/db.rs" },
  { key: "provenance", term: "Provenance", short: "Where a number came from: source file, row count, campaign, generation, seed, timestamp.",
    why: "A metric without provenance cannot be audited, and an unauditable metric is a rumour." },
  { key: "typed-triple", term: "Typed triple", short: "A fact shaped subject —relation→ object, carrying an evidence weight and a support count.",
    why: "It forces claims to be conditional and attributable instead of bare assertions.", where: "ai_scientist/graph.rs" },
  { key: "support", term: "Support", short: "How many independent observations back a fact.",
    why: "Support is your sample size. A confident-looking fact with support 1 is a guess." },
  { key: "confidence", term: "Confidence", short: "How consistent the observations behind a fact were, accrued by running statistics.",
    why: "High confidence with low support still means little — always read the pair together." },
  { key: "welford", term: "Welford statistics", short: "A numerically stable way to update a running mean and variance one observation at a time.",
    why: "It lets confidence grow incrementally over a stream of experiments without storing them all.", where: "ai_scientist/graph.rs" },
  { key: "falsification", term: "Falsification", short: "Testing a claim by trying to break it, rather than by collecting agreeable examples.",
    why: "It is the only procedure that reliably removes wrong beliefs. This whole platform is built around it.", where: "ai_scientist/theory.rs" },
  { key: "refutation", term: "Refutation", short: "A recorded failure of a hypothesis — kept permanently, never hidden.",
    why: "Refutations stop the loop from re-exploring dead ends, and they are the evidence that the successes are real." },
  { key: "negative-result", term: "Negative result", short: "Knowledge that something does not work, under stated conditions.",
    why: "In compute terms a negative result is as valuable as a positive one: it prunes the search space." },
  { key: "ablation", term: "Ablation", short: "Remove one component and re-measure; if nothing degrades, that component was not load-bearing.",
    why: "It converts a correlation into a causal claim — the step almost every 'mechanism' story skips.", where: "ai_scientist/theory.rs" },
  { key: "causal", term: "Causal vs. correlational", short: "A correlation says two things co-occur; a causal claim survives an intervention.",
    why: "Only causal claims transfer to new problems. Correlations often turn out to be confounds." },
  { key: "theory", term: "Theory", short: "A mechanism that made a falsifiable prediction and survived an ablation trying to refute it.",
    why: "It is the strongest epistemic status this platform grants — and it is still revisable." },
  { key: "statistical-power", term: "Statistical power", short: "Whether your sample is large enough to detect the effect you claim.",
    why: "A 100% win rate over 3 instances (p = 0.25) is not evidence. Read sample size before effect size — always." },
  { key: "wilcoxon", term: "Wilcoxon signed-rank", short: "A non-parametric paired test — it does not assume the differences are normally distributed.",
    why: "Solver scores are skewed and bounded, so parametric tests overstate significance.", where: "benchmark/stats.rs" },
  { key: "kill-criterion", term: "Kill-criterion", short: "A condition, fixed in advance, under which the idea is declared dead.",
    why: "Without it, any outcome can be rationalised into support. It is the cheapest defence against self-deception.", where: "experiments/specs/*.json" },
  { key: "pre-registration", term: "Pre-registration", short: "Writing the hypothesis and the kill-criterion before running the experiment.",
    why: "It removes the freedom to move the goalposts once you see the data." },
  { key: "reproducibility", term: "Cross-instance reproduction", short: "A rule counts as reproduced when it emerges independently from ≥2 instances' own records.",
    why: "One instance produces coincidences. Independent recurrence is the platform's internal replication test.", where: "ai_scientist/evaluation.rs" },
  { key: "signature", term: "Rule signature", short: "A canonical name for a mined pattern, e.g. Ordering:A<-B or Budget:X:scales.",
    why: "Naming a pattern lets you check whether the *same* pattern reappears elsewhere, rather than a vaguely similar story." },
  { key: "occam", term: "Occam penalty", short: "A complexity cost a new feature must overcome before it is admitted.",
    why: "It is what stopped an 11-feature descriptor that fit the data and still failed to generalise.", where: "ai_scientist/concept.rs" },
  { key: "out-of-sample", term: "Out-of-sample validation", short: "Measuring prediction on data not used to fit — here, leave-one-instance-out.",
    why: "In-sample fit is never sufficient; it is trivially improvable by adding parameters." },
  { key: "overfitting", term: "Overfitting", short: "Modelling noise in your training data as if it were signal.",
    why: "The reason the honest path here is to grow the dataset before growing the model." },
  { key: "foundation-scale", term: "Foundation scale", short: "The data volume at which a large model can learn general behaviour rather than memorise.",
    why: "With 18,570 examples the corpus is 27× short of the first milestone — worth knowing before training anything big.", where: "ai_scientist/dataset.rs" },
  { key: "operator-gap", term: "Operator gap", short: "A missing operator the meta-learner inferred from adjacency in the best solutions.",
    why: "This is a machine-generated research lead: two operators keep appearing together, so a fused operator may capture the effect more cheaply.", where: "ai_scientist/meta_learner.rs" },
  { key: "meta-learning", term: "Meta-learning", short: "Mining the experiment record itself for conditional rules about which algorithms work when.",
    why: "It turns raw runs into transferable strategy — the platform learning about its own learning.", where: "ai_scientist/meta_learner.rs" },
  { key: "ideation", term: "Ideation", short: "Generating candidate hypotheses cheaply, for a stricter process to filter.",
    why: "Diversity matters more than quality at this stage; the runtime is the filter." },
  { key: "hypothesis", term: "Hypothesis", short: "A proposed explanation stated so that evidence could contradict it.",
    why: "If no observation could disagree with it, it is not a hypothesis." },
  { key: "unverified", term: "Unverified", short: "A model-generated proposal that no experiment has yet tested.",
    why: "LLM output enters this platform as a hypothesis, never as a fact. Nothing typed in a console enters the knowledge graph." },
  { key: "adversarial-review", term: "Adversarial review", short: "Asking a reviewer (human or model) to attack a claim rather than agree with it.",
    why: "Refutation is checkable; agreement is not. A model is more useful as a skeptic than as an oracle." },
  { key: "reduction", term: "Reduction", short: "A mapping that turns problem A into problem B, so a B-solver solves A.",
    why: "It is the precise sense in which a QUBO engine 'applies' to scheduling or routing — and the limit of that claim.", where: "engine_v2/families.rs" },
  { key: "transfer", term: "Transfer", short: "Whether a strategy learned on one problem family works on another.",
    why: "Measured here, not assumed: a MaxCut-trained policy ranked operators on 9 of 12 non-MaxCut instances (ρ +0.747)." },
  { key: "evidence-tier", term: "Evidence tier", short: "Demonstrated here (T1), reducible in principle (T2), or open question (T3).",
    why: "It keeps 'we ran this' rigorously separate from 'this could work' — the distinction most technical marketing erases." },
  { key: "local-inference", term: "Local inference", short: "Running a language model on your own hardware, with no data leaving the machine.",
    why: "Cheap enough to use as a hypothesis generator, and private enough to point at unpublished research." },
  { key: "context-window", term: "Context window", short: "How many tokens a model can attend to at once.",
    why: "It bounds how much of the knowledge graph you can show a model in one question." },
  { key: "vram", term: "VRAM", short: "GPU memory a loaded model occupies.",
    why: "It decides which models can run at all, and whether two can be resident at once." },
  { key: "orchestrator", term: "Orchestrator", short: "The heartbeat that runs observe → learn → discover → theorise → plan → run → refute → record.",
    why: "It is what makes the scientist autonomous rather than a set of tools.", where: "ai_scientist/orchestrator.rs" },
  { key: "budget", term: "Budget cap", short: "A hard limit on ticks, experiments or wall-clock for an unattended run.",
    why: "It is what makes leaving an autonomous researcher running overnight a safe decision." },
  { key: "health-gate", term: "Health gate", short: "A cheap continuous check that halts the loop when an invariant breaks.",
    why: "An autonomous system without a stop condition eventually corrupts its own record.", where: "ai_scientist/monitor.rs" },
  { key: "method", term: "Method", short: "The fixed order of operations a researcher follows regardless of the result they hope for.",
    why: "Method is the difference between doing science and running code." },
  { key: "protocol", term: "Protocol", short: "A written procedure precise enough for someone else to repeat.",
    why: "If your procedure lives only in your head, your result is not reproducible." },
  { key: "uncertainty", term: "Uncertainty", short: "The stated bounds on what you actually know — confidence, support, and what remains untested.",
    why: "A result without its uncertainty is not a finding; it is a claim." },
];

const BY_KEY = new Map(GLOSSARY.map((t) => [t.key, t]));
export const term = (k: string) => BY_KEY.get(k);
